[UPD] feat(workflow): New wokflow definition
bibsys/DSpace pull request #20
Opened 2024-02-20 14:44 UTC by Pourbaix

Changed the workflow definition to have only the pdfattestation + review steps. Also, when a reviewer rejects a submission, it is set to the 'withdrawn' state.

2024-02-28 15:02 UTC, zannkukai requested changes

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> + */
COSMETIC : 
Don't hesitate to set `@author` and `@version` annotation into class docstring.
```
 * @author Michaël Pourbaix <michael.pourbaix@uclouvain.be>
 * @version $Revision$
 ```

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +public class ThesisReviewAction extends ReviewAction {
COSMETIC : Classname could be "UCLouvainThesisReviewAction" ?

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +    protected XmlWorkflowService xmlWorkflowService;
remove too (and test)

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +    protected static final String REJECT_REASON = "reason";
remove too: already defined into super classes

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +    private static final String SUBMITTER_IS_DELETED_PAGE = "submitter_deleted";
Remove these 3 lines:
  * (logicaly) Constants are defined into super class and should be used from it. The must not be redefine in this class.
  * (pratically) None of these constants are used in this class --> useless (a good IDE will prevent you about this problem)
  
--> Also check all import and remove unused imported classes.

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +        if (reason == null || 0 == reason.trim().length()) {
`0 == reason.trim().length()` --> `reason.isBlank()`

2024-02-28 15:02 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +        itemService.update(context, item);
COSMETIC : remove additionnal blank lines

2024-02-29 07:35 UTC, Pourbaix commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/xmlworkflow/actions/ThesisReviewAction.java
> +    private static final String SUBMITTER_IS_DELETED_PAGE = "submitter_deleted";
My IDE is shit, it didn't show me ... :face_with_spiral_eyes:

2024-03-04 07:16 UTC, zannkukai approved these changes

2024-03-04 07:48 UTC, merged