[ADD] feat(file-loader) File loader class for configuration files
bibsys/DSpace pull request #43
Opened 2024-04-10 13:27 UTC by Pourbaix

Added a new file loader class that allows to load a file and read it. It can also be used to determine if the file has change since the last time it was red. By using this class to load files content, it allow us to modify config files without restarting the application.

Authored-By: Michaël Pourbaix <michael.pourbaix@uclouvain.be>

2024-04-10 15:52 UTC, zannkukai requested changes
I don't understand where is the benefit of this class. You never really "reload" the file if it has been updated since last access. 
When you get data, you use File.readString|readAsByte that open the file, read the content, ... each time.

It think you need to use "factory pattern" in this case.
The factory loader class return instance of "ConfigurationFile" (that should be singleton classes themself). On "ConfigurationFile", you could cached the file content at first call of "read" functions. At second call, if file is updated, reload the content and update the cache ; otherwise return cache directly.

We could discuss about this ; It will be easier

2024-04-10 15:52 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/core/ConfigurationFileLoader.java
> +    public boolean isFileNewer(){
`isFileNewer()` --> `modified()` ?

2024-04-10 15:52 UTC, zannkukai commented on dspace-uclouvain/src/main/java/org/dspace/uclouvain/core/ConfigurationFileLoader.java
> +    }
Don't think it's a smart idea to keep `isError` flag ; just throws a `IOException` is files doesn't exists or can't be read.

2024-04-11 07:20 UTC, Pourbaix commented
Bullshit commit :wastebasket: will close and redo new PR after.

2024-04-11 07:20 UTC, closed without merging